# Generated by Django 3.1.1 on 2020-10-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionpedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
